### ISSUE TITLE
Deploy FE with Vercel

### ISSUE THREAD

**Issue by coleanthony1990** [Eat-Local/eat-local-fe#20]

**Comment by Ant-Shell** [comment]
Vercel has been setting up deploying a fork of this repo, as seen here: https://github.com/Ant-Shell/eatlocal

**Here is our new CI/CD workflow:**
- We should continue to push to https://github.com/Eat-Local/eat-local-fe for our CI
- Once all tests pass and code is reviewed, we can merge to main.
- After that, we can go to https://github.com/Ant-Shell/eatlocal and sync the changes for deploy to Vercel, by clicking "Sync fork", then "Update branch".
- More info about syncing a fork with its upstream, if interested: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
